### ISSUE TITLE
AttributeError: 'SemEvalProcessor' object has no attribute 'num_label'

### ISSUE THREAD

**Issue by filzahamjad** [yueyu1030/COSINE#19]
Traceback (most recent call last):
  File "main.py", line 113, in <module>
    main(args)
  File "main.py", line 13, in main
    train_dataset, relation_labels, num_labels, id2label, label2id, train_size  = load_and_cache_examples(args, tokenizer, mode="train")
  File "/Users/filzahamjad/Downloads/COSINE-main/data_loader_new.py", line 859, in load_and_cache_examples
    return dataset, processor.relation_labels, processor.num_label, processor.id2label, processor.label2id, size
AttributeError: 'SemEvalProcessor' object has no attribute 'num_label'

**Comment by yueyu1030** [comment]
Thanks for pointing this out! Actually, we don't use semeval dataset, so this object is actually not used.
