### ISSUE TITLE
TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by SageAgastya** [yueyu1030/COSINE#8]
There is a parameter missing, which I think is reflected by the error:

```
Traceback (most recent call last):
  File "main.py", line 114, in <module>
    main(args)
  File "main.py", line 42, in main
    trainer.selftrain(soft = args.soft_label)
  File "/home/ec2-user/SageMaker/weak_supervision/COSINE-main/trainer.py", line 215, in selftrain
    epoch_iterator.set_description("SelfTrain iter:%d Loss:%.3f m:%.3f" % (step, selftrain_loss/global_step, ))
TypeError: not enough arguments for format string
(/home/ec2-user/SageMaker/weak_supervision/env_p) sh-4.2$
```

What parameter should I add.
Thanks in advance.

**Comment by yueyu1030** [comment]
Hi, the `m:%.3f` is used for debugging.  You can simply remove these tokens. Thanks!
